import Head from "next/head";

import Header from "@components/Header";
import Container from "@components/Container";
import ProductCard from "@components/ProductCard";
import Button from "@components/Button";

import styles from "@styles/Home.module.scss";

// Test Data
import products from "@data/products.json";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Glamstock Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://app.snipcart.com" />
        <link rel="preconnect" href="https://cdn.snipcart.com" />
        <link
          rel="stylesheet"
          href="https://cdn.snipcart.com/themes/v3.2.1/default/snipcart.css"
        />
      </Head>

      <Header />

      <main>
        <Container>
          <h1>Glamstock</h1>
          <h2>Featured Products</h2>
          <ul className={styles.products}>
            {products.map((product) => {
              return (
                <ProductCard key={product.id}>
                  <img src={product.image} alt="addidas black backpack" />
                  <h3 className={styles.productTitle}>{product.title}</h3>
                  <p
                    className={styles.productPrice}
                  >{`$${product.price} NZD`}</p>
                  <Button
                    className="snipcart-add-item"
                    data-item-id={product.id}
                    data-item-price={product.price}
                    data-item-url="/"
                    data-item-description=""
                    data-item-image={product.image}
                    data-item-name={product.title}
                  >
                    Add to Cart
                  </Button>
                </ProductCard>
              );
            })}
          </ul>
        </Container>
      </main>

      <footer className={styles.footer}>
        &copy; GlamStock, {new Date().getFullYear()}
      </footer>
      <script
        async
        src="https://cdn.snipcart.com/themes/v3.2.1/default/snipcart.js"
      />
      <div
        hidden
        id="snipcart"
        data-api-key="MjUwZWIxNDItZTIzMi00NTM5LWExZDMtNTQ5YzZiNzQyM2RkNjM3Njk2MDUwNTc4MTQwOTI1"
      />
    </div>
  );
}
